/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Membership = IDL.Record({
  'active' : IDL.Bool,
  'tokenId' : IDL.Nat,
  'trialPeriod' : IDL.Bool,
  'owner' : IDL.Principal,
  'mintTimestamp' : Time,
});
export const MembershipTier = IDL.Variant({
  'trial' : IDL.Null,
  'free' : IDL.Null,
  'full' : IDL.Null,
});
export const ShareLinkPublic = IDL.Record({
  'id' : IDL.Text,
  'documentName' : IDL.Text,
  'active' : IDL.Bool,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'expiryTime' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelMembership' : IDL.Func([], [], []),
  'createShareLink' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLinkedApps' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
  'getMembership' : IDL.Func([IDL.Principal], [IDL.Opt(Membership)], ['query']),
  'getMembershipForCaller' : IDL.Func([], [IDL.Opt(Membership)], ['query']),
  'getMembershipForUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Membership)],
      ['query'],
    ),
  'getMembershipTier' : IDL.Func([IDL.Principal], [MembershipTier], ['query']),
  'getSelectedArts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getShareLink' : IDL.Func([IDL.Text], [IDL.Opt(ShareLinkPublic)], ['query']),
  'getTrialExpiryDate' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getUserByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMembershipActive' : IDL.Func([], [IDL.Bool], ['query']),
  'isTrialActive' : IDL.Func([], [IDL.Bool], ['query']),
  'linkAppPrincipal' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'mintMembership' : IDL.Func([], [], []),
  'revokeShareLink' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveSelectedArts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  'validateShareLink' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Membership = IDL.Record({
    'active' : IDL.Bool,
    'tokenId' : IDL.Nat,
    'trialPeriod' : IDL.Bool,
    'owner' : IDL.Principal,
    'mintTimestamp' : Time,
  });
  const MembershipTier = IDL.Variant({
    'trial' : IDL.Null,
    'free' : IDL.Null,
    'full' : IDL.Null,
  });
  const ShareLinkPublic = IDL.Record({
    'id' : IDL.Text,
    'documentName' : IDL.Text,
    'active' : IDL.Bool,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'expiryTime' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelMembership' : IDL.Func([], [], []),
    'createShareLink' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [IDL.Text], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLinkedApps' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Text)], ['query']),
    'getMembership' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Membership)],
        ['query'],
      ),
    'getMembershipForCaller' : IDL.Func([], [IDL.Opt(Membership)], ['query']),
    'getMembershipForUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Membership)],
        ['query'],
      ),
    'getMembershipTier' : IDL.Func(
        [IDL.Principal],
        [MembershipTier],
        ['query'],
      ),
    'getSelectedArts' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getShareLink' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ShareLinkPublic)],
        ['query'],
      ),
    'getTrialExpiryDate' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getUserByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMembershipActive' : IDL.Func([], [IDL.Bool], ['query']),
    'isTrialActive' : IDL.Func([], [IDL.Bool], ['query']),
    'linkAppPrincipal' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'mintMembership' : IDL.Func([], [], []),
    'revokeShareLink' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveSelectedArts' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
    'validateShareLink' : IDL.Func([IDL.Text, IDL.Text], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };