/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Time = IDL.Int;
export const Membership = IDL.Record({
  'active' : IDL.Bool,
  'tokenId' : IDL.Nat,
  'trialPeriod' : IDL.Bool,
  'owner' : IDL.Principal,
  'mintTimestamp' : Time,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelMembership' : IDL.Func([], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMembership' : IDL.Func([IDL.Principal], [IDL.Opt(Membership)], ['query']),
  'getMembershipForCaller' : IDL.Func([], [IDL.Opt(Membership)], ['query']),
  'getTrialExpiryDate' : IDL.Func([], [IDL.Opt(Time)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isMembershipActive' : IDL.Func([], [IDL.Bool], ['query']),
  'isTrialActive' : IDL.Func([], [IDL.Bool], ['query']),
  'mintMembership' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Time = IDL.Int;
  const Membership = IDL.Record({
    'active' : IDL.Bool,
    'tokenId' : IDL.Nat,
    'trialPeriod' : IDL.Bool,
    'owner' : IDL.Principal,
    'mintTimestamp' : Time,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelMembership' : IDL.Func([], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMembership' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Membership)],
        ['query'],
      ),
    'getMembershipForCaller' : IDL.Func([], [IDL.Opt(Membership)], ['query']),
    'getTrialExpiryDate' : IDL.Func([], [IDL.Opt(Time)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isMembershipActive' : IDL.Func([], [IDL.Bool], ['query']),
    'isTrialActive' : IDL.Func([], [IDL.Bool], ['query']),
    'mintMembership' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };